# Generated by Django 5.0.2 on 2024-03-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_categorie_fournisseur_produitnc_alter_produit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('em', 'Electronic'), ('cl', 'Clothing'), ('fo', 'Food')], default='em', max_length=2),
        ),
    ]
