# Generated by Django 5.0.2 on 2024-03-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_alter_produit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
