# Generated by Django 5.0.2 on 2024-03-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_alter_produit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
