# Generated by Django 5.0.2 on 2024-05-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
