# Generated by Django 5.0.2 on 2024-05-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
