# Generated by Django 5.0.2 on 2024-05-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0012_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
