# Generated by Django 5.0.2 on 2024-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0013_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[], default='em', max_length=2),
        ),
    ]
