# Generated by Django 5.0.2 on 2024-05-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0015_alter_produit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='totalCde',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
