# Generated by Django 5.0.2 on 2024-05-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0016_alter_commande_totalcde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
